### ISSUE TITLE
Hurdle Game 난이도 조절 안내

### ISSUE THREAD

**Issue by delena0702** [delena0702/TRI-TRY#10]
## Tic
이 게임에서 1틱은 5ms를 의미하며, 각 알람에 의한 동작은 특정 틱 수에 한 번씩 동작한다.

### 틱 관련

```
#define TIC_PLAYER 10
```
플레이어가 움직이는 틱 수이다. 즉, 플레이어는 50ms에 한 번씩 움직인다.

```
#define TIC_DIFFICULT 2000
```
난이도가 변하는 틱 수이다. 즉, 난이도는 10000ms = 10초에 한 번씩 변화한다.

```
unsigned int obtic = 10;	// tic of Obstacle moving
```
장애물이 움직이는 틱 수이다. 즉, 장애물은 50ms에 한 번씩 움직인다. 단, 게임 플레이 중 난이도 변경으로 값이 변화한다.

### 장애물 크기 관련

```
#define OBSTACLE_WIDTH 2
#define OBSTACLE_HEIGHT 3
```
장애물의 가로 세로 크기이다. 너무 크거나 0일 경우 예외처리는 되어있지 않으니 주의요망

### 게임 플레이 중 변화 요소들

- 장애물 간격 조절 : ```void makeNewObstacle(void)``` 참조
- 플레이어 물리엔진 : ```void hurdleTimerHandler(int sig)```의 ```if (tic % TIC_PLAYER == 0)``` 참조
- 난이도 조절 관련 : ```void hurdleTimerHandler(int sig)```의 ```if (tic % TIC_DIFFICULT == 0)``` 참조

**Comment by trevel1959** [comment]
### **SnakeGame 난이도 조정 관련 변수**


### 1. 뱀이 움직이는 시간 및 기본 단위
timer에서 _value와 _interval에 맞춰서 설정됨.
```
struct itimerval timer;
timer.it_value.tv_sec = 0;
timer.it_value.tv_usec = 250000;	//처음 1회에 대한 interval
timer.it_interval.tv_sec = 0;
timer.it_interval.tv_usec = 250000;	//한 번 실행 이후에 대한 interval
setitimer (ITIMER_REAL, &timer, NULL);	//위에서 정의한 시간마다 SIGALRM을 발생시킨다.
```

### 2. 뱀이 자라는 시간, 속도가 빨라지는 시간
위 시간마다 timer_handler()가 실행되어 본 게임 함수 내에서 뱀을 움직인 다음 int timeInterval이 1씩 증가한다. 그리고 다음 값마다 각각 뱀이 자라고, 속도가 빨라진다.

```
int snakeGrowthInterval = 30;	//!! 중요. 뱀은 매 30블럭을 움직일 때마다 자람.
int snakeSpeedInterval = 60;	//60칸 움직일 때마다 뱀 속도가 증가.
```

### 3. 속도가 빨라지는 공비
뱀 속도가 증가할 때마다 0.95배씩 사이 시간이 감소한다.
```
if(timeInterval % snakeSpeedInterval == 0){		// 뱀의 속도를 증가시켜준다.
	timer.it_value.tv_usec *= 0.95;		//처음 1회에 대한 interval
	timer.it_interval.tv_usec *= 0.95;	//그 이후 반복에 대한 interval
	setitimer (ITIMER_REAL, &timer, NULL);	//위에서 정의한 시간마다 SIGALRM을 발생시킨다.
```

**Comment by delena0702** [comment]
난이도 조정 완료
